### PR TITLE
Improve error handling not to panic

### PR DESCRIPTION
**Pull request by gunyarakun**
Improve error handling not to make new instance of response.

### CODE REVIEW

**Comment by gunyarakun** [comment]
In case you didn't know yet, you must enlarge max file descriptors with such as sysctl/ulimit.

**Comment by kentaro** [comment]
Thank you!

I was convinced that I had set the settings on max fds by `sysctl` on Mac OS X before the benchmark. Now I confirmed and found that `kern.maxfilesperproc` may not be enough...

```
$ sudo sysctl -n kern.maxfiles
20480

$ sudo sysctl -n kern.maxfilesperproc
8192
```

**Comment by kentaro** [comment]
Hmm, it's reproduced even after I set `kern.maxfilesperproc` to 65536...

**Comment by gunyarakun** [comment]
I modified these parameters on Mac OS X.

```
sysctl kern.maxfiles kern.maxfilesperproc net.inet.ip.portrange.first net.inet.tcp.msl
```

**Pull request merged**
